Adding refresh endpoint.
Financial-Times/brightcove-metadata-notifier pull request #8
Opened 2016-12-07 12:49 UTC by iulianp26

2016-12-07 13:51 UTC, tosan88 requested changes
Can you please also add a test case for this in `handler_test.go`?

2016-12-07 13:51 UTC, tosan88 commented on app.go
> +		EnvVar: "CMS_MEqTADATA_NOTIFIER_ADDR",
Typo

2016-12-07 13:51 UTC, tosan88 commented on app.go
> +	r.HandleFunc("/refresh", mm.handleRefresh).Methods("POST")
Can we have a `__reload` endpoint instead the naming to match with other apps?

2016-12-09 08:37 UTC, iulianp26 commented on app.go
> +		EnvVar: "CMS_MEqTADATA_NOTIFIER_ADDR",
Typo fixed.

2016-12-09 08:38 UTC, iulianp26 commented on app.go
> +	r.HandleFunc("/refresh", mm.handleRefresh).Methods("POST")
Done.

2016-12-09 09:40 UTC, tosan88 approved these changes

2016-12-09 09:40 UTC, tosan88 commented on circle.yml
> +    - go get github.com/mattn/goveralls
Nice one!

2016-12-13 08:36 UTC, kovacshuni approved these changes

2016-12-13 08:36 UTC, kovacshuni commented
great!

2016-12-13 08:36 UTC, kovacshuni commented
🎄

2016-12-13 11:40 UTC, merged